### ISSUE TITLE
Error: Container action is only supported on Linux

### ISSUE THREAD

**Issue by paulushub** [roryprimrose/set-vs-sdk-project-version#21]
Using this action to build WPF library, which means using `windows-latest` as docker image.
The build results in errors as shown below. Is there anyway out?

![image](https://github.com/roryprimrose/set-vs-sdk-project-version/assets/809351/d6adf2b3-f9af-4375-a199-0ebbca4afaad)

**Comment by roryprimrose** [comment]
Looks like you are using a really old Docker version of the action. The releases that came after were updated to use node which should work everywhere. 

Try this:

```
              - name: Version Visual Studio SDK projects
                uses: roryprimrose/set-vs-sdk-project-version@v1.0.6
```

**Comment by paulushub** [comment]
@roryprimrose Thanks so much. It resolved the issue.
